objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>For data management - Defines status of account (e.g.: Existing customer etc.).</description>
        <inlineHelpText>Defines status of account (e.g.: Existing customer etc.).</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Existing-Active</fullName>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                    <default>true</default>
                    <label>Prospect</label>
                </value>
                <value>
                    <fullName>Existing-Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Age__c</fullName>
        <description>DR Formula: TODAY()- DATEVALUE(CreatedDate)
changed by bazwe on 25.10.2017 to cover CloseDate of Opp minus Creation Date
changed by Lister on 24.11.2017</description>
        <formula>IF (  
	OR (
		ISPICKVAL( StageName , &apos;6 Closed/Won&apos;) , 
		ISPICKVAL( StageName , &apos;6 Closed/Lost&apos;)
		),
	CloseDate - DATEVALUE(CreatedDate),
	TODAY()- DATEVALUE(CreatedDate)
	)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Age</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Annual_contract_value__c</fullName>
        <description>ACV</description>
        <inlineHelpText>default values perp/1yr/2yrs/3yrs [kEUR]
AMS: 75 / 100 / 75 / 50
APAC: 80 / 80 / 40 / 30
EMEA: 75 / 75 / 40 / 40</inlineHelpText>
        <label>Annual contract value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/OpportunityNotificationsTest.cls
@isTest
public class OpportunityNotificationsTest {

    public static testMethod void testAll() {
        Account acc = new Account(Name = 'first', Status__c = 'Existing-Active', Industry = 'Banking', Website = 'www.aa.bb');
        insert acc;
        
        Opportunity opp1 = new Opportunity(AccountId = acc.id, Name = 'opp1', Type = 'Existing customer', CloseDate = system.today().addMonths(1), stageName = '0 Active (SQL)', NextStep = 'x', LeadSource = 'Banner');
        Opportunity opp2 = new Opportunity(AccountId = acc.id, Name = 'opp2', Type = 'Existing customer', CloseDate = system.today().addDays(10), stageName = '2 Qualification', NextStep = 'x', LeadSource = 'Banner', Annual_contract_value__c = 1);
        Opportunity opp3 = new Opportunity(AccountId = acc.id, Name = 'opp3', Type = 'Existing customer', CloseDate = system.today().addMonths(-1), stageName = '2 Qualification', NextStep = 'x', LeadSource = 'Banner', Annual_contract_value__c = 2);
        Opportunity opp4 = new Opportunity(AccountId = acc.id, Name = 'opp4', Type = 'Existing customer', CloseDate = system.today().addDays(1), stageName = '5 Negotiation/Closing', NextStep = 'x', LeadSource = 'Banner', Annual_contract_value__c = 2);
        insert new List<Opportunity> {opp1, opp2, opp3, opp4};
        
        Test.setCreatedDate(opp1.id, system.today().addYears(-1));
        Test.setCreatedDate(opp2.id, system.today().addYears(-1));
        Test.setCreatedDate(opp3.id, system.today().addYears(-1));
        Test.setCreatedDate(opp4.id, system.today().addYears(-1));
        opp3.CloseDate = system.today().addMonths(-1);
        update opp3;
        
        test.startTest();
        List<Opportunity> opps = [select id, description, Age__c, StageName, Annual_contract_value__c, OwnerId, name from opportunity];
        OpportunityNotificationsScheduler m2 = new OpportunityNotificationsScheduler();
        m2.execute(null);
        test.stopTest();
    }
}