objects/Account.object
<CustomObject>
    <fields>
        <fullName>AccountId18digit__c</fullName>
        <description>This is an admin field used for implementations and can be used for reports as well</description>
        <formula>CASESAFEID(Id)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This is an admin field used for implementations and can be used for reports as well</inlineHelpText>
        <label>AccountId18digit</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Age__c</fullName>
        <description>DR Formula: TODAY()- DATEVALUE(CreatedDate)
changed by bazwe on 25.10.2017 to cover CloseDate of Opp minus Creation Date
changed by Lister on 24.11.2017</description>
        <formula>IF (  
	OR (
		ISPICKVAL( StageName , &apos;6 Closed/Won&apos;) , 
		ISPICKVAL( StageName , &apos;6 Closed/Lost&apos;)
		),
	CloseDate - DATEVALUE(CreatedDate),
	TODAY()- DATEVALUE(CreatedDate)
	)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Age</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Annual_contract_value__c</fullName>
        <description>ACV</description>
        <inlineHelpText>default values perp/1yr/2yrs/3yrs [kEUR]
AMS: 75 / 100 / 75 / 50
APAC: 80 / 80 / 40 / 30
EMEA: 75 / 75 / 40 / 40</inlineHelpText>
        <label>Annual contract value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OpportunityId18digit__c</fullName>
        <description>This is an admin field used for implementations and can be used for reports as well</description>
        <formula>CASESAFEID(Id)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This is an admin field used for implementations and can be used for reports as well</inlineHelpText>
        <label>OpportunityId18digit</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/OpportunityNotificationsScheduler.cls
global class OpportunityNotificationsScheduler implements Schedulable {
    global void execute(SchedulableContext sc) {
        List<Opportunity> keyOpps = new List<Opportunity>([select id, name, description, Age__c, StageName, Annual_contract_value__c, OwnerId, AccountId, Account.Name, CloseDate, CreatedDate, OpportunityId18digit__c, Account.AccountId18digit__c, Owner.Isactive
                                                           from Opportunity where 
                                                          ((Age__c > 3 and StageName = '0 Active (SQL)' and Annual_contract_value__c > 0) or
                                                          ((StageName = '1 Prospecting (Discovering/Identifying)' or StageName = '2 Qualification' or StageName = '3 Evaluation') and Annual_contract_value__c > 0) or
                                                          (StageName != '6 Closed/Won' and StageName != '6 Closed/Lost' and StageName != '6 Closed/Pending' and Annual_contract_value__c > 0 and CloseDate < :system.today()) or
                                                          (CloseDate > :system.today() and CloseDate < :system.today().addDays(7) and (StageName = '4 Proposal' or StageName = '5 Negotiation/Closing') and Annual_contract_value__c > 0)
                                                          ) and Owner.Isactive = true]);
        
        OpportunityNotifications.NotifyOwner(keyOpps);
    }
}