objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <description>For data management - is being used for lead-account matching</description>
        <label>Email Domain</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>For data management - Defines status of account (e.g.: Existing customer etc.).</description>
        <inlineHelpText>Defines status of account (e.g.: Existing customer etc.).</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Existing-Active</fullName>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                    <default>true</default>
                    <label>Prospect</label>
                </value>
                <value>
                    <fullName>Existing-Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tier__c</fullName>
        <label>Tier</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Tier 1</fullName>
                </value>
                <value>
                    <fullName>Tier 2</fullName>
                </value>
                <value>
                    <fullName>Tier 3</fullName>
                    <default>true</default>
                    <label>Tier 3</label>
                </value>
                <value>
                    <fullName>Tier 4</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>geo__c</fullName>
        <description>For reporting on location</description>
        <inlineHelpText>Used for grouping in reports. 3 Geos available: EMEA, US, APAC</inlineHelpText>
        <label>Geo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>EMEA</fullName>
                    <color>#E27001</color>
                    <label>EMEA</label>
                </value>
                <value>
                    <fullName>APAC</fullName>
                    <color>#78C953</color>
                    <label>APAC</label>
                </value>
                <value>
                    <fullName>AMS</fullName>
                    <color>#3366FF</color>
                    <label>AMS</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Geo__c</fullName>
        <description>For reporting without having specify each country</description>
        <inlineHelpText>Used for grouping in reports. 3 Geos available: EMEA, US, APAC</inlineHelpText>
        <label>Geo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>APAC</fullName>
                </value>
                <value>
                    <fullName>AMS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tier__c</fullName>
        <label>Tier</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

classes/test_trgAccHandler.cls
@isTest
private class test_trgAccHandler
{
   public static testMethod void testMethod1()
   {
        Account newAcc = new Account(name = 'Lister Tech', website = 'www.listertechnologies.com', CurrencyIsoCode='GBP', Tier__c = 'Tier 1', Type='Customer', Status__c = 'Prospect', Geo__c = 'APAC', Industry='Banking', Email__c = 'listertechnologies.com');
        insert newAcc;

        Lead newLead = new Lead(LastName = 'Test lead', Company = 'Lister Tech', Email = 'testlead@listertechnologies.com', Status ='Contacted', CurrencyIsoCode = 'GBP');
        insert newLead;
        
        newAcc.Tier__c = 'Tier 2';
        update newAcc;
   }
   
   public static testMethod void testMethod2()
   {
        Account newAcc = new Account(name = 'Lister Tech', website = 'www.listertechnologies.com', CurrencyIsoCode='GBP', Tier__c = 'Tier 1', Type='Customer', Status__c = 'Prospect', Geo__c = 'APAC', Industry='Banking', Email__c = 'listertechnologies.com');
        insert newAcc;
        
        Lead newLead = new Lead(LastName = 'Test lead', Company = 'Lister Tech', Email = 'testlead@listertechnologies.com', Status ='Contacted', CurrencyIsoCode = 'GBP');
        insert newLead;
        
        newAcc.Email__c = 'lt.com';
        update newAcc;
   }
}