objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>For data management - Defines status of account (e.g.: Existing customer etc.).</description>
        <inlineHelpText>Defines status of account (e.g.: Existing customer etc.).</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Existing-Active</fullName>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                    <default>true</default>
                    <label>Prospect</label>
                </value>
                <value>
                    <fullName>Existing-Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>geo__c</fullName>
        <description>For reporting on location</description>
        <inlineHelpText>Used for grouping in reports. 3 Geos available: EMEA, US, APAC</inlineHelpText>
        <label>Geo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>EMEA</fullName>
                    <color>#E27001</color>
                    <label>EMEA</label>
                </value>
                <value>
                    <fullName>APAC</fullName>
                    <color>#78C953</color>
                    <label>APAC</label>
                </value>
                <value>
                    <fullName>AMS</fullName>
                    <color>#3366FF</color>
                    <label>AMS</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Geo__c</fullName>
        <description>For reporting on location</description>
        <inlineHelpText>Used for grouping in reports. 3 Geos available: EMEA, US, APAC</inlineHelpText>
        <label>Geo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>APAC</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>AMS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Annual_contract_value__c</fullName>
        <description>ACV</description>
        <inlineHelpText>default values perp/1yr/2yrs/3yrs [kEUR]
AMS: 75 / 100 / 75 / 50
APAC: 80 / 80 / 40 / 30
EMEA: 75 / 75 / 40 / 40</inlineHelpText>
        <label>Annual contract value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Geo__c</fullName>
        <formula>TEXT(Account.geo__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Geo</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tri_Close_Reason__c</fullName>
        <description>Vertiba 3/10/14 - debrief information to help assess why deal was won or lost</description>
        <inlineHelpText>Select one or more values that best describe the reason for closing.</inlineHelpText>
        <label>Close Reason</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Lost - Company Budget Constraints</fullName>
                </value>
                <value>
                    <fullName>Lost - Duplicate</fullName>
                </value>
                <value>
                    <fullName>Lost - No Decision</fullName>
                </value>
                <value>
                    <fullName>Lost - no Opportunity</fullName>
                    <label>Lost - No Opportunity</label>
                </value>
                <value>
                    <fullName>Lost on Price</fullName>
                </value>
                <value>
                    <fullName>Lost - Open source</fullName>
                </value>
                <value>
                    <fullName>Lost - Other Reason</fullName>
                </value>
                <value>
                    <fullName>Lost - Product Features</fullName>
                </value>
                <value>
                    <fullName>Lost - Project Abandoned</fullName>
                </value>
                <value>
                    <fullName>Lost to Competitor</fullName>
                </value>
                <value>
                    <fullName>Won from Competitor</fullName>
                </value>
                <value>
                    <fullName>Won on Price</fullName>
                </value>
                <value>
                    <fullName>Won - Other Reason</fullName>
                </value>
                <value>
                    <fullName>Won - Product Features</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/Test_Trg_Opportunity.cls
/* - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Title           : Test_Trg_Opportunity 
Author          : Lister Technologies
Description     : Test Class
Trigger         : Trg_Opportunity
Handler Class   : Opportunitytriggerhandler
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - */
@isTest(seealldata=true)
private class Test_Trg_Opportunity {

    static testMethod void myUnitTest() {
        
        Account acc = new Account(Name='Test Account',Website='test@test.com',Type='Customer',Status__c='Existing-Active',geo__c='EMEA',Industry='Aerospace & Defense',CurrencyIsoCode='EUR');
        insert acc;    
        
        Contact con = new Contact(AccountId=acc.id,lastname='Test contact');
        insert con;                   
        
        Opportunity opp = new Opportunity(Name='Test opp',AccountId=acc.Id,Annual_contract_value__c=1000,Type='Existing customer',CloseDate=date.today(),StageName='5 Negotiation/Closing',Amount=0.00,CurrencyIsoCode='EUR');
        insert opp;
        
        OpportunityContactRole ocr = new OpportunityContactRole(OpportunityId=opp.Id,ContactId=con.Id,role='Business User');
        insert ocr;
        
        quote quo = new quote(Name='Test quote',OpportunityId=opp.Id);
        insert quo;
        
        opp.StageName = '6 Closed/Won';
        opp.Tri_Close_Reason__c='Won on Price';
        update opp;
        
    }
}