objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>For data management - Defines status of account (e.g.: Existing customer etc.).</description>
        <inlineHelpText>Defines status of account (e.g.: Existing customer etc.).</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Existing-Active</fullName>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                    <default>true</default>
                    <label>Prospect</label>
                </value>
                <value>
                    <fullName>Existing-Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>geo__c</fullName>
        <description>For reporting on location</description>
        <inlineHelpText>Used for grouping in reports. 3 Geos available: EMEA, US, APAC</inlineHelpText>
        <label>Geo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>EMEA</fullName>
                    <color>#E27001</color>
                    <label>EMEA</label>
                </value>
                <value>
                    <fullName>APAC</fullName>
                    <color>#78C953</color>
                    <label>APAC</label>
                </value>
                <value>
                    <fullName>AMS</fullName>
                    <color>#3366FF</color>
                    <label>AMS</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>ACV_mgmt_commit_in_Euro__c</fullName>
        <label>ACV mgmt commit in Euro</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Annual_contract_value__c</fullName>
        <description>ACV</description>
        <inlineHelpText>default values perp/1yr/2yrs/3yrs [kEUR]
AMS: 75 / 100 / 75 / 50
APAC: 80 / 80 / 40 / 30
EMEA: 75 / 75 / 40 / 40</inlineHelpText>
        <label>Annual contract value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Geo__c</fullName>
        <formula>TEXT(Account.geo__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Geo</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LIC_FYM_mgmt_commit__c</fullName>
        <label>ACV mgmt commit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>License_Type__c</fullName>
        <description>Choose the license type for the opportunity</description>
        <inlineHelpText>Choose the license type for the opportunity</inlineHelpText>
        <label>License Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Perpetual</fullName>
                </value>
                <value>
                    <fullName>Subscription</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tri_Close_Reason__c</fullName>
        <description>Vertiba 3/10/14 - debrief information to help assess why deal was won or lost</description>
        <inlineHelpText>Select one or more values that best describe the reason for closing.</inlineHelpText>
        <label>Close Reason</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Lost - Company Budget Constraints</fullName>
                </value>
                <value>
                    <fullName>Lost - Duplicate</fullName>
                </value>
                <value>
                    <fullName>Lost - No Decision</fullName>
                </value>
                <value>
                    <fullName>Lost - no Opportunity</fullName>
                    <label>Lost - No Opportunity</label>
                </value>
                <value>
                    <fullName>Lost on Price</fullName>
                </value>
                <value>
                    <fullName>Lost - Open source</fullName>
                </value>
                <value>
                    <fullName>Lost - Other Reason</fullName>
                </value>
                <value>
                    <fullName>Lost - Product Features</fullName>
                </value>
                <value>
                    <fullName>Lost - Project Abandoned</fullName>
                </value>
                <value>
                    <fullName>Lost to Competitor</fullName>
                </value>
                <value>
                    <fullName>Won from Competitor</fullName>
                </value>
                <value>
                    <fullName>Won on Price</fullName>
                </value>
                <value>
                    <fullName>Won - Other Reason</fullName>
                </value>
                <value>
                    <fullName>Won - Product Features</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tri_Debrief_Comments__c</fullName>
        <description>Vertiba 3/10/14 - debrief information</description>
        <inlineHelpText>Additional information on reason won or lost, other important comments</inlineHelpText>
        <label>Debrief Comments</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>isenable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>is update</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/TestCurrencyConvHandler_Opp.cls
@isTest
public class TestCurrencyConvHandler_Opp {
 public static testmethod void acvCurrencyConversion(){
        
        List<Opportunity> oppList = new List<Opportunity>();
        List<Opportunity> oppUpdateList = new List<Opportunity>();
        List<Opportunity> oppResultList = new List<Opportunity>();
        Account acc = new Account();
        acc.Name = 'LK Test Solutions';
        acc.Type = 'Customer';
        acc.Website = 'www.lksoln.com';
        acc.CurrencyIsoCode = 'EUR';
        acc.Status__c='Existing-Active';
        acc.geo__c='APAC';
        acc.Industry='Electronics';
        insert acc;
        
        Opportunity opp = new Opportunity();
        opp.Name='Test1';
        opp.License_Type__c = 'Perpetual';
        opp.Annual_contract_value__c = 300;
        opp.ACV_mgmt_commit_in_Euro__c = 400;
        opp.AccountId=acc.Id;
        opp.StageName='3 Evaluation';
        opp.type='Existing Customer';
        opp.CloseDate = Date.newInstance(2017, 09, 4);
        opp.LeadSource = 'MQL(Marketing Sourced)';
        opp.CurrencyIsoCode = 'AUD';
        opp.NextStep = 'Test';
        opp.isenable__c = true;
        oppList.add(opp);
        
        Opportunity opp1 = new Opportunity();
        opp1.Name='Test2';
        opp1.AccountId=acc.Id;
        opp.License_Type__c = 'Perpetual';
        opp.Annual_contract_value__c = 300;
        opp.ACV_mgmt_commit_in_Euro__c = 400;
        opp.isenable__c = true;
        opp.Tri_Close_Reason__c = 'Lost to Competitor';
        opp1.StageName='6 Closed/Won';
        opp1.type='Existing Customer';
        opp1.CloseDate = Date.newInstance(2017, 10, 1);
        opp1.LeadSource = 'MQL(Marketing Sourced)';
        opp1.CurrencyIsoCode = 'CHF';
        opp1.NextStep = 'Test';
        oppList.add(opp1);
        
        Opportunity opp2 = new Opportunity();
        opp2.Name='Test3';
        opp2.AccountId=acc.Id;
        opp.License_Type__c = 'Perpetual';
        opp.Annual_contract_value__c = 300;
        opp.ACV_mgmt_commit_in_Euro__c = 400;
        opp.isenable__c = true;
        opp2.StageName='6 Closed/Lost';
        opp2.Tri_Debrief_Comments__c = 'comments';
        opp2.Tri_Close_Reason__c = 'Lost to Competitor';
        opp2.type='Existing Customer';
        opp2.CloseDate = Date.newInstance(2017, 01, 3);
        opp2.LeadSource = 'MQL(Marketing Sourced)';
        opp2.CurrencyIsoCode = 'NZD';
        opp2.NextStep = 'Test';
        oppList.add(opp2);
        
        Opportunity opp3 = new Opportunity();
        opp3.Name='Test4';
        opp3.AccountId=acc.Id;
        opp3.StageName='3 Evaluation';
        opp3.type='Existing Customer';
        opp3.CloseDate = Date.newInstance(2017, 08, 26);
        opp3.LeadSource = 'MQL(Marketing Sourced)';
        opp3.CurrencyIsoCode = 'GBP';
        opp3.NextStep = 'Test';
        oppList.add(opp3);
            
        test.startTest();
        insert oppList;
        opp.LIC_FYM_mgmt_commit__c = 15;
        oppUpdateList.add(opp);
        opp1.LIC_FYM_mgmt_commit__c = 13;
        oppUpdateList.add(opp1);
        opp2.LIC_FYM_mgmt_commit__c = 14;
        oppUpdateList.add(opp2);
        opp3.LIC_FYM_mgmt_commit__c = 16;
        oppUpdateList.add(opp3);
        
        update oppUpdateList;
        List<Opportunity> opptyUpdateList = [Select CreatedDate,Id,CurrencyIsoCode,LIC_FYM_mgmt_commit__c,ACV_mgmt_commit_in_Euro__c from Opportunity where id in : oppUpdateList];
        CurrencyConversionHandler.handleCurrencyConversion(opptyUpdateList);
        
        oppResultList = [Select Name,ACV_mgmt_commit_in_Euro__c from Opportunity where id in : oppUpdateList];
        /*
        for(Opportunity oppResult:oppResultList){
            Decimal acv_value = oppResult.ACV_mgmt_commit_in_Euro__c;
            if(oppResult.Name=='Test1')
            system.assertEquals(10.07,acv_value.setscale(2));
            else if(oppResult.Name=='Test2')
                system.assertEquals(12.04,acv_value.setscale(2));
            else if(oppResult.Name=='Test3')
                system.assertEquals(8.97,acv_value.setscale(2));
            else if(oppResult.Name=='Test4')
                system.assertEquals(19.28,acv_value.setscale(2));
        } */
        test.stopTest(); 
        
    }
}