objects/Account.object
<CustomObject>
    <fields>
        <fullName>geo__c</fullName>
        <description>For reporting on location</description>
        <inlineHelpText>Used for grouping in reports. 3 Geos available: EMEA, US, APAC</inlineHelpText>
        <label>Geo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>EMEA</fullName>
                    <color>#E27001</color>
                    <label>EMEA</label>
                </value>
                <value>
                    <fullName>APAC</fullName>
                    <color>#78C953</color>
                    <label>APAC</label>
                </value>
                <value>
                    <fullName>AMS</fullName>
                    <color>#3366FF</color>
                    <label>AMS</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Geo__c</fullName>
        <description>For reporting on location</description>
        <inlineHelpText>Used for grouping in reports. 3 Geos available: EMEA, US, APAC</inlineHelpText>
        <label>Geo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>APAC</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>AMS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>contact_status__c</fullName>
        <description>For Lead/Contact Status</description>
        <label>Contact Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Solar flare</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Re-open</fullName>
                </value>
                <value>
                    <fullName>Rejected/Disqualified</fullName>
                </value>
                <value>
                    <fullName>Initiated</fullName>
                </value>
                <value>
                    <fullName>Contacted</fullName>
                </value>
                <value>
                    <fullName>Not Now</fullName>
                </value>
                <value>
                    <fullName>Qualified - (SQL)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Annual_contract_value__c</fullName>
        <description>ACV</description>
        <inlineHelpText>default values perp/1yr/2yrs/3yrs [kEUR]
AMS: 75 / 100 / 75 / 50
APAC: 80 / 80 / 40 / 30
EMEA: 75 / 75 / 40 / 40</inlineHelpText>
        <label>Annual contract value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Geo__c</fullName>
        <formula>TEXT(Account.geo__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Geo</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tri_Close_Reason__c</fullName>
        <description>Vertiba 3/10/14 - debrief information to help assess why deal was won or lost</description>
        <inlineHelpText>Select one or more values that best describe the reason for closing.</inlineHelpText>
        <label>Close Reason</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Lost - Company Budget Constraints</fullName>
                </value>
                <value>
                    <fullName>Lost - Duplicate</fullName>
                </value>
                <value>
                    <fullName>Lost - No Decision</fullName>
                </value>
                <value>
                    <fullName>Lost - no Opportunity</fullName>
                    <label>Lost - No Opportunity</label>
                </value>
                <value>
                    <fullName>Lost on Price</fullName>
                </value>
                <value>
                    <fullName>Lost - Open source</fullName>
                </value>
                <value>
                    <fullName>Lost - Other Reason</fullName>
                </value>
                <value>
                    <fullName>Lost - Product Features</fullName>
                </value>
                <value>
                    <fullName>Lost - Project Abandoned</fullName>
                </value>
                <value>
                    <fullName>Lost to Competitor</fullName>
                </value>
                <value>
                    <fullName>Won from Competitor</fullName>
                </value>
                <value>
                    <fullName>Won on Price</fullName>
                </value>
                <value>
                    <fullName>Won - Other Reason</fullName>
                </value>
                <value>
                    <fullName>Won - Product Features</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/Test_cls_OpportunityViewPage.cls
@isTest
public class Test_cls_OpportunityViewPage {
    static testMethod void unittest(){
        Account acc = new Account(Name='Test Account');
        insert acc;
        Contact con = new Contact(lastname='Testlast',AccountId=acc.Id,Email='test@test1.com',Geo__c='APAC',contact_status__c='Solar flare');
        insert con;
        Opportunity opp = new Opportunity(Name='Test opp',AccountId=acc.Id,Annual_contract_value__c=1000 ,StageName='6 Closed/Won',CloseDate=date.today(),Tri_Close_Reason__c='Won on Price');
        insert opp;
        OpportunityContactRole ocr = new OpportunityContactRole(OpportunityId=opp.Id,ContactId=con.Id,role='Business User');
        insert ocr;        
        quote quo = new quote(Name='Test quote',OpportunityId=opp.Id);
        insert quo;
        
        PageReference pg = Page.OpportunityViewPage;
        Test.setCurrentPage(pg);
        
        ApexPages.currentPage().getParameters().put('Id', opp.id);
        
        ApexPages.StandardController sc = new ApexPages.StandardController(opp);                                
        cls_OpportunityViewPage controller = new cls_OpportunityViewPage(sc);
        controller.SaveClosedate();
        controller.closePopup();
    }
}