objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <description>For data management - is being used for lead-account matching</description>
        <label>Email Domain</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>For data management - Defines status of account (e.g.: Existing customer etc.).</description>
        <inlineHelpText>Defines status of account (e.g.: Existing customer etc.).</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Existing-Active</fullName>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                    <default>true</default>
                    <label>Prospect</label>
                </value>
                <value>
                    <fullName>Existing-Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>geo__c</fullName>
        <description>For reporting on location</description>
        <inlineHelpText>Used for grouping in reports. 3 Geos available: EMEA, US, APAC</inlineHelpText>
        <label>Geo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>EMEA</fullName>
                    <color>#E27001</color>
                    <label>EMEA</label>
                </value>
                <value>
                    <fullName>APAC</fullName>
                    <color>#78C953</color>
                    <label>APAC</label>
                </value>
                <value>
                    <fullName>AMS</fullName>
                    <color>#3366FF</color>
                    <label>AMS</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Geo__c</fullName>
        <description>For reporting on location</description>
        <inlineHelpText>Used for grouping in reports. 3 Geos available: EMEA, US, APAC</inlineHelpText>
        <label>Geo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>APAC</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>AMS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>contact_status__c</fullName>
        <description>For Lead/Contact Status</description>
        <label>Contact Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Solar flare</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Re-open</fullName>
                </value>
                <value>
                    <fullName>Rejected/Disqualified</fullName>
                </value>
                <value>
                    <fullName>Initiated</fullName>
                </value>
                <value>
                    <fullName>Contacted</fullName>
                </value>
                <value>
                    <fullName>Not Now</fullName>
                </value>
                <value>
                    <fullName>Qualified - (SQL)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>dr_funnel__c</fullName>
        <description>For funnel grid</description>
        <label>Funnel</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>MRL</fullName>
                </value>
                <value>
                    <fullName>MVL</fullName>
                </value>
                <value>
                    <fullName>MTL</fullName>
                </value>
                <value>
                    <fullName>MQL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Geo__c</fullName>
        <description>For reporting without having specify each country</description>
        <inlineHelpText>Used for grouping in reports. 3 Geos available: EMEA, US, APAC</inlineHelpText>
        <label>Geo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>APAC</fullName>
                </value>
                <value>
                    <fullName>AMS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>dr_funnel__c</fullName>
        <description>For funnel grid, important field for lead assignment</description>
        <inlineHelpText>Defines the type of lead. Either MRL (raw lead), MVL (validated lead), MTL (targeted lead) or MQL (qualify lead). MRL &amp; MVL are mostly only relevant for Marketing (still need nurturing), MTL &amp; MQL can be relevant for Sales.</inlineHelpText>
        <label>Funnel</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>MRL</fullName>
                </value>
                <value>
                    <fullName>MVL</fullName>
                </value>
                <value>
                    <fullName>MTL</fullName>
                </value>
                <value>
                    <fullName>MQL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Annual_contract_value__c</fullName>
        <description>ACV</description>
        <inlineHelpText>default values perp/1yr/2yrs/3yrs [kEUR]
AMS: 75 / 100 / 75 / 50
APAC: 80 / 80 / 40 / 30
EMEA: 75 / 75 / 40 / 40</inlineHelpText>
        <label>Annual contract value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Geo__c</fullName>
        <formula>TEXT(Account.geo__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Geo</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/Test_AutoLeadConversionBatch.cls
/* - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Title           : Test_AutoLeadConversionBatch
Author          : Lister Technologies
Description     : Test Class
Test Class      : AutoLeadConversionBatch
Schedule Class  : Schedule_AutoLeadConversionBatch
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - */
@istest
public class Test_AutoLeadConversionBatch {
    static testMethod void unittest1(){
        Lead ld1 = new Lead(Company='Test Acc',lastname='Test Last',Email='test@test12345.com',Status='Open',CurrencyIsoCode='EUR',dr_funnel__c='MQL');
        insert ld1;
        
        Lead ld2 = new Lead(Company='Test Acc',lastname='Test Last',Email='test1@test12345.com',Status='Open',CurrencyIsoCode='EUR',dr_funnel__c='MQL');
        insert ld2;
        
        Lead ld3 = new Lead(Company='Test Acc',lastname='Test Last',Email='test1@test3.com',Status='Open',CurrencyIsoCode='EUR',dr_funnel__c='MQL');
        insert ld3;
        
        Account acc1 = new Account(Name='TestAccount',Email__c='test12345.com',Website='testwebsite.com',Type='Customer',CurrencyIsoCode='EUR',Status__c='Prospect',geo__c='APAC',Industry='Electronic');
        insert acc1;
        
        Account acc2 = new Account(Name='TestAccount2',Email__c='test3.com',Website='testwebsite.com',Type='Customer',CurrencyIsoCode='EUR',Status__c='Prospect',geo__c='APAC',Industry='Electronic');
        insert acc2;
        
        Contact con1 = new Contact(lastname='Testlast',AccountId=acc1.Id,Email='test@test123456.com',Geo__c='APAC',contact_status__c='Solar flare');
        insert con1;
        
        Opportunity opp1 = new Opportunity(Name='TestOpp',Annual_contract_value__c=100,AccountId=acc1.Id,StageName='5 Negotiation/Closing',CloseDate=date.today());
        insert opp1;        
        
        OpportunityContactRole ocr = new OpportunityContactRole(OpportunityId=opp1.Id,ContactId=con1.Id,role='Business User');
        insert ocr;
        
        quote quo = new quote(Name='Test quote',OpportunityId=opp1.Id);
        insert quo;
        
        Test.startTest();
        Schedule_AutoLeadConversionBatch salcb = new Schedule_AutoLeadConversionBatch();             
         // Schedule the test job
         string sch='0 0 12 * * ?'; 
         String jobId = system.schedule('test',sch,salcb);
        Test.stopTest();
    }
}