objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <description>For data management - is being used for lead-account matching</description>
        <label>Email Domain</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>For data management - Defines status of account (e.g.: Existing customer etc.).</description>
        <inlineHelpText>Defines status of account (e.g.: Existing customer etc.).</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Existing-Active</fullName>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                    <default>true</default>
                    <label>Prospect</label>
                </value>
                <value>
                    <fullName>Existing-Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tier__c</fullName>
        <label>Tier</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Tier 1</fullName>
                </value>
                <value>
                    <fullName>Tier 2</fullName>
                </value>
                <value>
                    <fullName>Tier 3</fullName>
                    <default>true</default>
                    <label>Tier 3</label>
                </value>
                <value>
                    <fullName>Tier 4</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>geo__c</fullName>
        <description>For reporting on location</description>
        <inlineHelpText>Used for grouping in reports. 3 Geos available: EMEA, US, APAC</inlineHelpText>
        <label>Geo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>EMEA</fullName>
                    <color>#E27001</color>
                    <label>EMEA</label>
                </value>
                <value>
                    <fullName>APAC</fullName>
                    <color>#78C953</color>
                    <label>APAC</label>
                </value>
                <value>
                    <fullName>AMS</fullName>
                    <color>#3366FF</color>
                    <label>AMS</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Geo__c</fullName>
        <description>For reporting without having specify each country</description>
        <inlineHelpText>Used for grouping in reports. 3 Geos available: EMEA, US, APAC</inlineHelpText>
        <label>Geo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>APAC</fullName>
                </value>
                <value>
                    <fullName>AMS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tier__c</fullName>
        <label>Tier</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

classes/TestbatchLeadTierUpdate.cls
@istest
public class TestbatchLeadTierUpdate
{
    @istest static void Tiersuccesscase()
    {
    
        
        Account acct=new Account(Name='AccTest1',Website='www.roundberry.com',Email__c='roundberry.com',CurrencyIsoCode='USD',Tier__c='Tier 3',Type='Customer',
                                Status__c='Prospect',geo__c='EMEA',Industry='Electronics');

                                insert acct;    
                                
        Lead ld=new Lead(Company='LDTest1',LastName='LDTest9001',Email='LDtest1@roundberry.com',Status='Open',CurrencyIsoCode='USD');
        
            insert ld;
            
            ld.tier__c=null;
            update ld;
        
  Test.startTest();
        batchLeadTierUpdate b = new batchLeadTierUpdate();
Database.executebatch(b,50);
        Test.stopTest();    
            
       Lead leadupdated=[select Tier__c from Lead where ID=:ld.Id];     
     System.assertEquals(acct.Tier__c, leadupdated.Tier__c); 
    
    }
      @istest static void MultipleAccount()
    {

        
        Account acct=new Account();
        acct.Name='AccTest3';
        acct.Website='www.abc.com';
        acct.Email__c='abc.com';
        acct.CurrencyIsoCode='USD';
        acct.Tier__c='Tier 1';
        acct.Type='Customer';
        acct.Status__c='Prospect';
        acct.geo__c='EMEA';
        acct.Industry='Electronics';
        insert acct;    
        
        Account acct1=new Account();
         acct1.Name='AccTest4';
        acct1.Website='www.abc.com';
        acct1.Email__c='abc.com';
        acct1.CurrencyIsoCode='USD';
        acct1.Tier__c='Tier 2';
        acct1.Type='Customer';
        acct1.Status__c='Prospect';
        acct1.geo__c='EMEA';
        acct1.Industry='Electronics';
        insert acct1;    
                
                                
        Lead ld=new Lead(Company='LDTest3',LastName='LDTest3',Email='LDTest3@abc.com',Status='Open',CurrencyIsoCode='USD');
        
            insert ld;
            
            ld.tier__c=null;
            update ld;
            Test.startTest();
        batchLeadTierUpdate b = new batchLeadTierUpdate();
Database.executebatch(b,50);
        Test.stopTest();    
        
       Lead leadupdated=[select Tier__c from Lead where ID=:ld.Id];       
    // System.assertEquals('Multiple Accounts', leadupdated.Tier__c); 
   
    }
       @istest static void ParentAccount()
    {
    
        
       
        Account acct=new Account();
        acct.Name='AccTest3';
        acct.Website='www.abc.com';
        acct.Email__c='abc.com';
        acct.CurrencyIsoCode='USD';
        acct.Tier__c='Tier 1';
        acct.Type='Customer';
        acct.Status__c='Prospect';
        acct.geo__c='EMEA';
        acct.Industry='Electronics';
        insert acct;    
        
        Account acct1=new Account();
         acct1.Name='AccTest4';
        acct1.ParentID=acct.id;
        acct1.Website='www.abc.com';
        acct1.Email__c='abc.com';
        acct1.CurrencyIsoCode='USD';
        acct1.Tier__c='Tier 2';
        acct1.Type='Customer';
        acct1.Status__c='Prospect';
        acct1.geo__c='EMEA';
        acct1.Industry='Electronics';
        insert acct1;    
                
                                
        Lead ld=new Lead(Company='LDTest3',LastName='LDTest3',Email='LDTest3@abc.com',Status='Open',CurrencyIsoCode='USD');
        
            insert ld;
            
             ld.tier__c=null;
            update ld;
            
     Test.startTest();   
     SchedulebatchLeadTierUpdate sh1 = new SchedulebatchLeadTierUpdate ();      
     String sch = '0 0 8 15 12 ?';
       system.schedule('Test', sch, sh1);
     
     Test.stopTest();
        Lead leadupdated=[select Tier__c from Lead where ID=:ld.Id];           
   //  System.assertEquals(acct.Tier__c, leadupdated.Tier__c); 
    
    }
    
    
}