objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>ACV_in_Euro__c</fullName>
        <label>ACV in Euro</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ACV_mgmt_commit_in_Euro__c</fullName>
        <label>ACV mgmt commit in Euro</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Annual_contract_value__c</fullName>
        <description>ACV</description>
        <inlineHelpText>default values perp/1yr/2yrs/3yrs [kEUR]
AMS: 75 / 100 / 75 / 50
APAC: 80 / 80 / 40 / 30
EMEA: 75 / 75 / 40 / 40</inlineHelpText>
        <label>Annual contract value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>LIC_FYM_mgmt_commit__c</fullName>
        <label>ACV mgmt commit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>License_Type__c</fullName>
        <description>Choose the license type for the opportunity</description>
        <inlineHelpText>Choose the license type for the opportunity</inlineHelpText>
        <label>License Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Perpetual</fullName>
                </value>
                <value>
                    <fullName>Subscription</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Mgmt_Expected_NACV_in_Euro__c</fullName>
        <description>Expected value for the deal
Request by noefi 17.01.2018</description>
        <label>Mgmt Expected NACV in Euro</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Normalized_ACVMgmtCommit__c</fullName>
        <formula>IF( ISPICKVAL( License_Type__c , &apos;Perpetual&apos;) ,LIC_FYM_mgmt_commit__c*0.5 , LIC_FYM_mgmt_commit__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Normalized Annual Contract  value Management Commit</inlineHelpText>
        <label>NACV Mgmt Commit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Normalized_ACV__c</fullName>
        <formula>IF( ISPICKVAL( License_Type__c , &apos;Perpetual&apos;) ,  Annual_contract_value__c * 0.5, Annual_contract_value__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Normalized Annual contract value</inlineHelpText>
        <label>NACV</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Normalized_ACVinEuro__c</fullName>
        <formula>IF( ISPICKVAL( License_Type__c , &apos;Perpetual&apos;) ,  ACV_in_Euro__c *0.5,  ACV_in_Euro__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>NACV in Euro</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subscription_Term__c</fullName>
        <description>Choose the subscription term for a subscription opportunity. If the opportunity is for perpetual licenses choose NA.</description>
        <inlineHelpText>Choose the subscription term for a subscription opportunity. If the opportunity is for perpetual licenses choose NA.</inlineHelpText>
        <label>Subscription Term in years</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>License_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>NA</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Pipeline_NACV_in_Euro__c</fullName>
        <description>Forecasted value of the deal by the sales rep.
Request by noefi 17.01.2018</description>
        <label>Total Pipeline NACV in Euro</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_contract_value__c</fullName>
        <description>ACV * subscription term 
Depricated as of October 2017 - CPQ writes TCV into new TCV field</description>
        <inlineHelpText>ACV * subscription term</inlineHelpText>
        <label>Total contract value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Weighted_Normalized_ACV__c</fullName>
        <formula>IF( ISPICKVAL( License_Type__c ,&apos;Perpetual&apos;) ,  Weigthed_Annual_contract_value__c * 0.5, Weigthed_Annual_contract_value__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Weighted Normalized Annual contract value</inlineHelpText>
        <label>WNACV</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Weigthed_Pipeline_NACV_in_Euro__c</fullName>
        <description>Value forecasted by the rep but adjusted by the probability of it being realized, depending on the opportunity stage.
Request by noefi 17.01.2018</description>
        <label>Weigthed Pipeline NACV in Euro</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/CurrencyConvHandler_Opp.cls
/*
        Name: CurrencyConvHandler_Opp
        Discription: Class to Convert other currency into euro
        Created by: Sunil
        Test Class: TestCurrencyConvHandler_Opp

    Change History
     *********************************************************************************************************************************************
     ModifiedBy        Date          Ticket No.      Requested By      Description                                                             Tag
     *********************************************************************************************************************************************                                                                                                                                                                                      
*/


public class CurrencyConvHandler_Opp {
    
    public static void handleCurrencyConversion(List<Opportunity> Opportunities){
        
        Date maxDate;
        Date minDate;
        Date createdDate;
        Set<String> currencyCodes = new Set<String>();
        Set<Date> dateofRateExchanges = new Set<Date>();
        List<DatedConversionRate> conversionRateList = new List<DatedConversionRate>();
        Map<String,DatedConversionRate> exchangeRateMap = new Map<String,DatedConversionRate>();
        List<Opportunity> oppUpdateList = new List<Opportunity>();
        Map<Id,double> convertedCurr = new Map<Id,double>();
        Set<Id> oppId = new Set<Id>();
        
        for(Opportunity opp:Opportunities){
            if(opp.CreatedDate!= null )
            createdDate = opp.CreatedDate.date();
            else
                createdDate = Date.today();
            if(opp.CurrencyIsoCode!= null)
                currencyCodes.add(opp.CurrencyIsoCode);
            dateofRateExchanges.add(createdDate);
            if(maxDate == null || createdDate > maxDate)    
                maxDate = createdDate;
            if(minDate == null || createdDate < minDate)
                minDate = createdDate;    
        }
        
        System.debug('maxDate::::MinDate:::::'+maxDate+':::::::'+minDate);
        if(maxDate!=null && minDate!=null && currencyCodes.size()!=0){
            
            conversionRateList = [select ConversionRate,Isocode,NextStartDate,StartDate from 
                                  DatedConversionRate where IsoCode in:currencyCodes and  
                                  (NextStartDate>=:minDate and StartDate<=:maxDate)];
            System.debug('conversionRateList:::::'+conversionRateList.size());
            if(conversionRateList.size()!=0){
                for(DatedConversionRate dcr:conversionRateList){
                    for(Date rateExchangedate:dateofRateExchanges){
                        if((rateExchangedate >= dcr.StartDate)&&(rateExchangedate <= dcr.NextStartDate)){
                            exchangeRateMap.put(rateExchangedate+'-'+dcr.Isocode,dcr);
                        }
                    }}
                
                // Conversion to Euro
                List<Opportunity> updatedOpp = new List<Opportunity>();
                for(Opportunity opp:Opportunities){
                    DatedConversionRate dateCon = new DatedConversionRate();
                    double Acv_In_Euro =0;
                    if(opp.CreatedDate!= null )
                    dateCon = exchangeRateMap.get(opp.CreatedDate.date()+'-'+opp.CurrencyIsoCode);
                    else
                        dateCon = exchangeRateMap.get(Date.today()+'-'+opp.CurrencyIsoCode);
                    if(dateCon!=null && dateCon.ConversionRate!=0){
                        if(opp.StageName == '6 Closed/Lost')
                        {
                            opp.Weigthed_Pipeline_NACV_in_Euro__c = 0;
                            opp.Total_Pipeline_NACV_in_Euro__c = 0;
                            opp.Mgmt_Expected_NACV_in_Euro__c = 0;
                            //divya
                            if(opp.License_Type__c == 'Perpetual')
                                {
                                    system.debug('license typepcl : '+ opp.License_Type__c);
                                    system.debug('Annual contract value pcl: '+ opp.Annual_contract_value__c);
                                    system.debug('Annual contract value convertedpcl: '+ dateCon.ConversionRate);
                                    opp.Total_contract_value__c = (opp.Annual_contract_value__c != null)?opp.Annual_contract_value__c/dateCon.ConversionRate:null;
                                    system.debug('tcv perpetualcl : '+ opp.Total_contract_value__c);
                                }
                           
                                else
                                if(opp.License_Type__c == 'Subscription')
                                {
                                    system.debug('license typesubcl : '+ opp.License_Type__c);
                                    system.debug('Annual contract value subcl : '+ opp.Annual_contract_value__c);
                                    system.debug('Annual contract value convertedsubcl : '+ dateCon.ConversionRate);
                                  
                                    opp.Total_contract_value__c = (opp.Annual_contract_value__c != null && opp.Subscription_Term__c != null)?((opp.Annual_contract_value__c/dateCon.ConversionRate)* Integer.valueOf(opp.Subscription_Term__c)):null;
                                    system.debug('Tcvsubcl: '+ opp.Total_contract_value__c);
                                }  
                            //divya
                        }
                        else
                            if(opp.StageName == '6 Closed/Won')
                            {
                                opp.Weigthed_Pipeline_NACV_in_Euro__c = opp.Normalized_ACVinEuro__c;
                                opp.Total_Pipeline_NACV_in_Euro__c = opp.Normalized_ACVinEuro__c;
                                opp.Mgmt_Expected_NACV_in_Euro__c = opp.Normalized_ACVinEuro__c;
                                //divya
                                if(opp.License_Type__c == 'Perpetual')
                                {
                                    opp.Total_contract_value__c = opp.ACV_in_Euro__c;
                                }
                                else
                                if(opp.License_Type__c == 'Subscription')
                                {
                                    
                                    opp.Total_contract_value__c = (opp.ACV_in_Euro__c != null && opp.Subscription_Term__c != null )?opp.ACV_in_Euro__c * Integer.valueOf(opp.Subscription_Term__c):null;
                                }
                                
                                //divya
                            }
                        else
                        {
                            if(opp.StageName !='0 Active (SQL)') {
                            opp.Weigthed_Pipeline_NACV_in_Euro__c = opp.Weighted_Normalized_ACV__c/dateCon.ConversionRate;
                            opp.Total_Pipeline_NACV_in_Euro__c = opp.Normalized_ACV__c/dateCon.ConversionRate;
                            opp.Mgmt_Expected_NACV_in_Euro__c = opp.Normalized_ACVMgmtCommit__c/dateCon.ConversionRate;
                            
                            }
                            //divya
                            if(opp.License_Type__c == 'Perpetual')
                                {
                                    system.debug('license typep!=0 : '+ opp.License_Type__c);
                                    system.debug('Annual contract value p!=0 : '+ opp.Annual_contract_value__c);
                                    system.debug('Annual contract value converted p!=0 : '+ dateCon.ConversionRate);
                                 
                                    opp.Total_contract_value__c = (opp.Annual_contract_value__c != null)?opp.Annual_contract_value__c/dateCon.ConversionRate:null;
                                    system.debug('tcv perpetual!=0 : '+ opp.Total_contract_value__c);
                                }
                                else
                                if(opp.License_Type__c == 'Subscription')
                                {
                                    {
                                        system.debug('license typesub!=0 : '+ opp.License_Type__c);
                                        system.debug('Annual contract value sub!=0 : '+ opp.Annual_contract_value__c);
                                        system.debug('Annual contract value converted sub!=0 : '+ dateCon.ConversionRate);
                                        
                                        opp.Total_contract_value__c = (opp.Annual_contract_value__c != null && opp.Subscription_Term__c != null)?((opp.Annual_contract_value__c/dateCon.ConversionRate).setScale(2)) * Integer.valueOf(opp.Subscription_Term__c):null;
                                        system.debug('Tcvsub!=0 : '+ opp.Total_contract_value__c);
                                    }
                                    
                                }
                            //}
                            //divya
                        } 
                            
                        
                        updatedOpp.add(opp);
                        /*Acv_In_Euro = opp.LIC_FYM_mgmt_commit__c/dateCon.ConversionRate; 
                        if(opp.ACV_mgmt_commit_in_Euro__c!=Acv_In_Euro){
                            oppId.add(opp.Id);
                            convertedCurr.put(opp.Id, Acv_In_Euro);} */
                    }
                }
                 System.debug('updatedOpp-->'+updatedOpp);
                //if(updatedOpp.size()!=0)  
                //        update updatedOpp;     
                            
            }
        
    }
}
}